import { defineSlotRecipe } from "@pandacss/dev";

export const flipbookShell = defineSlotRecipe({
	className: "flipbook-shell",
	description: "Recipe for the flipbook structural layout",
	slots: [
		"root",
		"header",
		"stage",
		"stageInner",
		"paper",
		"front",
		"back",
		"controlBtn",
		"bottomNav",
		"mobileStageInner",
	],
	base: {
		root: {
			display: "flex",
			flexDirection: "column",
			height: "100dvh",
			width: "100vw",
			overflow: "hidden",
			bg: "gray.950",
			color: "white",
			position: "relative",
		},
		header: {
			display: "flex",
			justifyContent: "space-between",
			alignItems: "center",
			p: "4",
			zIndex: 20,
			w: "full",
			background: "linear-gradient(to bottom, rgba(0,0,0,0.8), transparent)",
		},
		stage: {
			flex: 1,
			display: "flex",
			justifyContent: "center",
			alignItems: "center",
			position: "relative",
			w: "full",
			minHeight: 0, // Critical for flexbox overflow
			padding: "20px",
			perspective: "2000px",
			perspectiveOrigin: "center center",
		},
		stageInner: {
			position: "relative",
			width: "100%",
			height: "100%",
			maxWidth: "1400px",
			transformStyle: "preserve-3d",
			display: "flex",
			justifyContent: "center",
			alignItems: "center",
		},
		paper: {
			position: "absolute",
			width: "50%",
			height: "100%",
			top: 0,
			right: 0,
			transformStyle: "preserve-3d",
			transition: "transform 0.6s cubic-bezier(0.645, 0.045, 0.355, 1)",
			transformOrigin: "left center",
			zIndex: "var(--z-index)",
			transform: "rotateY(0deg)", // Initial state
			backfaceVisibility: "hidden",
			background: "transparent",
			_motionReduce: {
				transition: "none",
			},
			"&[data-turned='true']": {
				transform: "rotateY(-180deg)",
				zIndex: "var(--z-index)",
				transition:
					"transform 0.6s cubic-bezier(0.645, 0.045, 0.355, 1), z-index 0s 0.3s",
				_motionReduce: {
					transition: "none", // Instant swap for reduced motion
				},
			},
		},
		front: {
			position: "absolute",
			width: "100%",
			height: "100%",
			backfaceVisibility: "hidden",
			bg: "gray.900",
			overflow: "hidden",
			// spine decoration
			_before: {
				content: '""',
				position: "absolute",
				left: 0,
				top: 0,
				bottom: 0,
				width: "30px",
				background: "linear-gradient(to right, rgba(0,0,0,0.4), transparent)",
				zIndex: 2,
			},
			"& img, & picture": {
				objectFit: "contain",
				objectPosition: "left center",
				width: "100%!",
				height: "100%!",
				maxHeight: "100%!",
				maxWidth: "100%!",
				display: "block",
			},
		},
		back: {
			position: "absolute",
			width: "100%",
			height: "100%",
			backfaceVisibility: "hidden",
			transform: "rotateY(180deg)",
			bg: "gray.900",
			overflow: "hidden",
			// spine decoration
			_before: {
				content: '""',
				position: "absolute",
				right: 0,
				top: 0,
				bottom: 0,
				width: "30px",
				background: "linear-gradient(to left, rgba(0,0,0,0.4), transparent)",
				zIndex: 2,
			},
			"& img, & picture": {
				objectFit: "contain",
				objectPosition: "right center",
				width: "100%!",
				height: "100%!",
				maxHeight: "100%!",
				maxWidth: "100%!",
				display: "block",
			},
		},
		mobileStageInner: {
			position: "relative",
			width: "100%",
			height: "100%",
			display: "flex",
			justifyContent: "center",
			alignItems: "center",
			"& img, & picture": {
				objectFit: "contain",
				width: "100%!",
				height: "100%!",
				maxHeight: "100%!",
				maxWidth: "100%!",
				display: "block",
			},
		},
		controlBtn: {
			position: "absolute",
			top: "50%",
			transform: "translateY(-50%)",
			zIndex: 10,
			bg: "black/40",
			color: "white",
			_hover: { bg: "black/60" },
			borderRadius: "full",
			w: "44px",
			h: "44px",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			cursor: "pointer",
			"&[data-side='left']": { left: "4" },
			"&[data-side='right']": { right: "4" },
		},
		bottomNav: {
			display: "flex",
			justifyContent: "space-between",
			alignItems: "center",
			p: "4",
			zIndex: 20,
			background: "linear-gradient(to top, rgba(0,0,0,0.8), transparent)",
			gap: "2",
			w: "full",
		},
	},
});
